typography_spectrum: 0.039570560213178396
color:
  brandStrength: 0.3870662513654679
  lightness: 0.602502575609833
  saturation: 0.06043983483687043
  rhythmicContrast: 0.624990769661963
  brandColors:
    - '#FDFFFA'
    - '#221010'
    - '#464938'
    - '#ACA85E'
    - '#846B55'
layout_spectrum: 0.041267725406214595
analytics:
  google: UA-82840632-1
author:
  name: Myles Blackwood
  email: myles@blackwood.bike
  url: 'http://myles.blackwood.bike'
name: ':: blackwood.bike ::'
navigation:
  - name: Momentummag.com
    url: 'https://momentummag.com'
    type: external
title: ':: blackwood.bike ::'
description: a site about the blackwoods and their bicycles
